# Generated by Django 3.1.6 on 2021-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corpera',
            fields=[
                ('corpera_id', models.AutoField(primary_key=True, serialize=False)),
                ('corpera_name', models.CharField(max_length=100)),
                ('corpera_discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
