# Generated by Django 3.1.6 on 2021-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_auto_20210412_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
