# Generated by Django 3.1.6 on 2021-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20210412_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpera',
            name='annotated',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='corpera',
            name='anonymization',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='corpera',
            name='research',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
