# Generated by Django 3.1.6 on 2021-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_corpera_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpera',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='infrastructure/files'),
        ),
    ]
