# Generated by Django 3.1.6 on 2021-04-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_auto_20210426_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpera',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
