# Generated by Django 3.1.6 on 2021-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_auto_20210503_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpora',
            name='category',
            field=models.CharField(choices=[('patient records', 'patient record'), ('forum', 'forum'), ('guideline', 'guideline'), ('terminology system', 'terminology system'), ('other', 'other')], default='patient record', max_length=50),
        ),
        migrations.AlterField(
            model_name='corpora',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
