# Generated by Django 3.1.6 on 2021-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_auto_20210503_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpora',
            name='discipline',
            field=models.CharField(choices=[('other', 'other'), ('general practition', 'general practition'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Cardiothoracic surgery', 'Cardiothoracic surgery'), ('Dermatology', 'Dermatology'), ('Surgery', 'Surgery'), ('Internal medicine', 'Internal medicine'), ('Otorhinolaryngology', 'Otorhinolaryngology'), ('Pediatrics', 'Pediatrics'), ('Pulmonology', 'Pulmonology'), ('Gastroenterology', 'Gastroenterology'), ('Medical microbiology', 'Medical microbiology'), ('Neurosurgery', 'Neurosurgery'), ('Neurology', 'Neurology'), ('Nuclear medicine', 'Nuclear medicine'), ('Gynaecology', 'Gynaecology'), ('Ophthalmology', 'Ophthalmology'), ('Oncology', 'Oncology'), ('Orthopedics', 'Orthopedics'), ('Pathology', 'Pathology'), ('Plastic surgery', 'Plastic surgery'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Rheumatology', 'Rheumatology'), ('Physical medicine and rehabilitation', 'Physical medicine and rehabilitation'), ('Emergency medicine', 'Emergency medicine'), ('Sports medicine', 'Sports medicine'), ('Urology', 'Urology')], default='huisarts', max_length=50),
        ),
    ]
